/*
 * Selling Partner API for Finances
 *
 * The Selling Partner API for Finances helps you obtain financial information relevant to a seller's business. You can obtain financial events for a given order, financial event group, or date range without having to wait until a statement period closes. You can also obtain financial event groups for a given date range.
 *
 * OpenAPI spec version: v0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace FikaAmazonAPI.AmazonSpApiSDK.Models.Finances
{
    /// <summary>
    ///     The response schema for the listFinancialEvents operation.
    /// </summary>
    [DataContract]
    public class ListFinancialEventsResponse : IEquatable<ListFinancialEventsResponse>, IValidatableObject
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="ListFinancialEventsResponse" /> class.
        /// </summary>
        /// <param name="Payload">The payload for the listFinancialEvents operation..</param>
        /// <param name="Errors">One or more unexpected errors occurred during the listFinancialEvents operation..</param>
        public ListFinancialEventsResponse(ListFinancialEventsPayload Payload = default, ErrorList Errors = default)
        {
            this.Payload = Payload;
            this.Errors = Errors;
        }

        public ListFinancialEventsResponse()
        {
            Payload = default;
            Errors = default;
        }

        /// <summary>
        ///     The payload for the listFinancialEvents operation.
        /// </summary>
        /// <value>The payload for the listFinancialEvents operation.</value>
        [DataMember(Name = "payload", EmitDefaultValue = false)]
        public ListFinancialEventsPayload Payload { get; set; }

        /// <summary>
        ///     One or more unexpected errors occurred during the listFinancialEvents operation.
        /// </summary>
        /// <value>One or more unexpected errors occurred during the listFinancialEvents operation.</value>
        [DataMember(Name = "errors", EmitDefaultValue = false)]
        public ErrorList Errors { get; set; }

        /// <summary>
        ///     Returns true if ListFinancialEventsResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of ListFinancialEventsResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ListFinancialEventsResponse input)
        {
            if (input == null)
                return false;

            return
                (
                    Payload == input.Payload ||
                    (Payload != null &&
                     Payload.Equals(input.Payload))
                ) &&
                (
                    Errors == input.Errors ||
                    (Errors != null &&
                     Errors.Equals(input.Errors))
                );
        }

        /// <summary>
        ///     To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }

        /// <summary>
        ///     Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ListFinancialEventsResponse {\n");
            sb.Append("  Payload: ").Append(Payload).Append("\n");
            sb.Append("  Errors: ").Append(Errors).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        ///     Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        ///     Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as ListFinancialEventsResponse);
        }

        /// <summary>
        ///     Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                if (Payload != null)
                    hashCode = hashCode * 59 + Payload.GetHashCode();
                if (Errors != null)
                    hashCode = hashCode * 59 + Errors.GetHashCode();
                return hashCode;
            }
        }
    }
}