/*
 * Selling Partner API for Listings Items
 *
 * The Selling Partner API for Listings Items (Listings Items API) provides programmatic access to selling partner listings on Amazon. Use this API in collaboration with the Selling Partner API for Product Type Definitions, which you use to retrieve the information about Amazon product types needed to use the Listings Items API.  For more information, see the [Listings Items API Use Case Guide](doc:listings-items-api-v2021-08-01-use-case-guide).
 *
 * OpenAPI spec version: 2021-08-01
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace FikaAmazonAPI.AmazonSpApiSDK.Models.ListingsItems
{
    /// <summary>
    ///     Offer details of a listings item for an Amazon marketplace.
    /// </summary>
    [DataContract]
    public class ItemOfferByMarketplace : IEquatable<ItemOfferByMarketplace>, IValidatableObject
    {
        /// <summary>
        ///     Type of offer for the listings item.
        /// </summary>
        /// <value>Type of offer for the listings item.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum OfferTypeEnum
        {
            /// <summary>
            ///     Enum B2C for value: B2C
            /// </summary>
            [EnumMember(Value = "B2C")] B2C = 1,

            /// <summary>
            ///     Enum B2B for value: B2B
            /// </summary>
            [EnumMember(Value = "B2B")] B2B = 2
        }

        /// <summary>
        ///     Initializes a new instance of the <see cref="ItemOfferByMarketplace" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ItemOfferByMarketplace()
        {
        }

        /// <summary>
        ///     Initializes a new instance of the <see cref="ItemOfferByMarketplace" /> class.
        /// </summary>
        /// <param name="marketplaceId">Amazon marketplace identifier. (required).</param>
        /// <param name="offerType">Type of offer for the listings item. (required).</param>
        /// <param name="price">Purchase price of the listings item (required).</param>
        /// <param name="points">points.</param>
        public ItemOfferByMarketplace(string marketplaceId = default, OfferTypeEnum offerType = default,
            Money price = default, Points points = default)
        {
            // to ensure "marketplaceId" is required (not null)
            if (marketplaceId == null)
                throw new InvalidDataException(
                    "marketplaceId is a required property for ItemOfferByMarketplace and cannot be null");
            MarketplaceId = marketplaceId;
            // to ensure "offerType" is required (not null)
            if (offerType == null)
                throw new InvalidDataException(
                    "offerType is a required property for ItemOfferByMarketplace and cannot be null");
            OfferType = offerType;
            // to ensure "price" is required (not null)
            if (price == null)
                throw new InvalidDataException(
                    "price is a required property for ItemOfferByMarketplace and cannot be null");
            Price = price;
            Points = points;
        }

        /// <summary>
        ///     Type of offer for the listings item.
        /// </summary>
        /// <value>Type of offer for the listings item.</value>
        [DataMember(Name = "offerType", EmitDefaultValue = false)]
        public OfferTypeEnum OfferType { get; set; }

        /// <summary>
        ///     Amazon marketplace identifier.
        /// </summary>
        /// <value>Amazon marketplace identifier.</value>
        [DataMember(Name = "marketplaceId", EmitDefaultValue = false)]
        public string MarketplaceId { get; set; }


        /// <summary>
        ///     Purchase price of the listings item
        /// </summary>
        /// <value>Purchase price of the listings item</value>
        [DataMember(Name = "price", EmitDefaultValue = false)]
        public Money Price { get; set; }

        /// <summary>
        ///     Gets or Sets Points
        /// </summary>
        [DataMember(Name = "points", EmitDefaultValue = false)]
        public Points Points { get; set; }

        /// <summary>
        ///     Returns true if ItemOfferByMarketplace instances are equal
        /// </summary>
        /// <param name="input">Instance of ItemOfferByMarketplace to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ItemOfferByMarketplace input)
        {
            if (input == null)
                return false;

            return
                (
                    MarketplaceId == input.MarketplaceId ||
                    (MarketplaceId != null &&
                     MarketplaceId.Equals(input.MarketplaceId))
                ) &&
                (
                    OfferType == input.OfferType ||
                    (OfferType != null &&
                     OfferType.Equals(input.OfferType))
                ) &&
                (
                    Price == input.Price ||
                    (Price != null &&
                     Price.Equals(input.Price))
                ) &&
                (
                    Points == input.Points ||
                    (Points != null &&
                     Points.Equals(input.Points))
                );
        }

        /// <summary>
        ///     To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }

        /// <summary>
        ///     Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ItemOfferByMarketplace {\n");
            sb.Append("  MarketplaceId: ").Append(MarketplaceId).Append("\n");
            sb.Append("  OfferType: ").Append(OfferType).Append("\n");
            sb.Append("  Price: ").Append(Price).Append("\n");
            sb.Append("  Points: ").Append(Points).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        ///     Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        ///     Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as ItemOfferByMarketplace);
        }

        /// <summary>
        ///     Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                if (MarketplaceId != null)
                    hashCode = hashCode * 59 + MarketplaceId.GetHashCode();
                if (OfferType != null)
                    hashCode = hashCode * 59 + OfferType.GetHashCode();
                if (Price != null)
                    hashCode = hashCode * 59 + Price.GetHashCode();
                if (Points != null)
                    hashCode = hashCode * 59 + Points.GetHashCode();
                return hashCode;
            }
        }
    }
}