/*
 * Selling Partner API for Fulfillment Outbound
 *
 * The Selling Partner API for Fulfillment Outbound lets you create applications that help a seller fulfill Multi-Channel Fulfillment orders using their inventory in Amazon's fulfillment network. You can get information on both potential and existing fulfillment orders.
 *
 * OpenAPI spec version: v0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace FikaAmazonAPI.AmazonSpApiSDK.Models.FulfillmentOutbound
{
    /// <summary>
    ///     Item information for a fulfillment order preview.
    /// </summary>
    [DataContract]
    public class GetFulfillmentPreviewItem : IEquatable<GetFulfillmentPreviewItem>, IValidatableObject
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="GetFulfillmentPreviewItem" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        public GetFulfillmentPreviewItem()
        {
        }

        /// <summary>
        ///     Initializes a new instance of the <see cref="GetFulfillmentPreviewItem" /> class.
        /// </summary>
        /// <param name="SellerSKU">The seller SKU of the item. (required).</param>
        /// <param name="Quantity">Quantity (required).</param>
        /// <param name="SellerFulfillmentOrderItemId">
        ///     A fulfillment order item identifier that the seller creates to track items
        ///     in the fulfillment preview. (required).
        /// </param>
        public GetFulfillmentPreviewItem(string SellerSKU = default, int Quantity = default,
            string SellerFulfillmentOrderItemId = default)
        {
            // to ensure "SellerSKU" is required (not null)
            if (SellerSKU == null)
                throw new InvalidDataException(
                    "SellerSKU is a required property for GetFulfillmentPreviewItem and cannot be null");
            this.SellerSKU = SellerSKU;
            // to ensure "Quantity" is required (not null)
            if (Quantity == null)
                throw new InvalidDataException(
                    "Quantity is a required property for GetFulfillmentPreviewItem and cannot be null");
            this.Quantity = Quantity;
            // to ensure "SellerFulfillmentOrderItemId" is required (not null)
            if (SellerFulfillmentOrderItemId == null)
                throw new InvalidDataException(
                    "SellerFulfillmentOrderItemId is a required property for GetFulfillmentPreviewItem and cannot be null");
            this.SellerFulfillmentOrderItemId = SellerFulfillmentOrderItemId;
        }

        /// <summary>
        ///     The seller SKU of the item.
        /// </summary>
        /// <value>The seller SKU of the item.</value>
        [DataMember(Name = "sellerSku", EmitDefaultValue = false)]
        public string SellerSKU { get; set; }

        /// <summary>
        ///     Gets or Sets Quantity
        /// </summary>
        [DataMember(Name = "quantity", EmitDefaultValue = false)]
        public int Quantity { get; set; }

        /// <summary>
        ///     A fulfillment order item identifier that the seller creates to track items in the fulfillment preview.
        /// </summary>
        /// <value>A fulfillment order item identifier that the seller creates to track items in the fulfillment preview.</value>
        [DataMember(Name = "sellerFulfillmentOrderItemId", EmitDefaultValue = false)]
        public string SellerFulfillmentOrderItemId { get; set; }

        /// <summary>
        ///     Returns true if GetFulfillmentPreviewItem instances are equal
        /// </summary>
        /// <param name="input">Instance of GetFulfillmentPreviewItem to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetFulfillmentPreviewItem input)
        {
            if (input == null)
                return false;

            return
                (
                    SellerSKU == input.SellerSKU ||
                    (SellerSKU != null &&
                     SellerSKU.Equals(input.SellerSKU))
                ) &&
                (
                    Quantity == input.Quantity ||
                    (Quantity != null &&
                     Quantity.Equals(input.Quantity))
                ) &&
                (
                    SellerFulfillmentOrderItemId == input.SellerFulfillmentOrderItemId ||
                    (SellerFulfillmentOrderItemId != null &&
                     SellerFulfillmentOrderItemId.Equals(input.SellerFulfillmentOrderItemId))
                );
        }

        /// <summary>
        ///     To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // SellerSKU (string) maxLength
            if (SellerSKU != null && SellerSKU.Length > 50)
                yield return new ValidationResult("Invalid value for SellerSKU, length must be less than 50.",
                    new[] { "SellerSKU" });

            // SellerFulfillmentOrderItemId (string) maxLength
            if (SellerFulfillmentOrderItemId != null && SellerFulfillmentOrderItemId.Length > 50)
                yield return new ValidationResult(
                    "Invalid value for SellerFulfillmentOrderItemId, length must be less than 50.",
                    new[] { "SellerFulfillmentOrderItemId" });
        }

        /// <summary>
        ///     Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GetFulfillmentPreviewItem {\n");
            sb.Append("  SellerSKU: ").Append(SellerSKU).Append("\n");
            sb.Append("  Quantity: ").Append(Quantity).Append("\n");
            sb.Append("  SellerFulfillmentOrderItemId: ").Append(SellerFulfillmentOrderItemId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        ///     Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        ///     Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as GetFulfillmentPreviewItem);
        }

        /// <summary>
        ///     Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                if (SellerSKU != null)
                    hashCode = hashCode * 59 + SellerSKU.GetHashCode();
                if (Quantity != null)
                    hashCode = hashCode * 59 + Quantity.GetHashCode();
                if (SellerFulfillmentOrderItemId != null)
                    hashCode = hashCode * 59 + SellerFulfillmentOrderItemId.GetHashCode();
                return hashCode;
            }
        }
    }
}