/*
 * Selling Partner API for Services
 *
 * With the Services API, you can build applications that help service providers get and modify their service orders.
 *
 * OpenAPI spec version: v1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace FikaAmazonAPI.AmazonSpApiSDK.Models.Services
{
    /// <summary>
    ///     Warning returned when the request is successful but execution have some important callouts on basis of which API
    ///     clients should take defined actions.
    /// </summary>
    [DataContract]
    public class Warning : IEquatable<Warning>, IValidatableObject
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="Warning" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        public Warning()
        {
        }

        /// <summary>
        ///     Initializes a new instance of the <see cref="Warning" /> class.
        /// </summary>
        /// <param name="Code">An warning code that identifies the type of warning that occurred. (required).</param>
        /// <param name="Message">A message that describes the warning condition in a human-readable form. (required).</param>
        /// <param name="Details">Additional details that can help the caller understand or address the warning..</param>
        public Warning(string Code = default, string Message = default, string Details = default)
        {
            // to ensure "Code" is required (not null)
            if (Code == null)
                throw new InvalidDataException("Code is a required property for Warning and cannot be null");
            this.Code = Code;
            // to ensure "Message" is required (not null)
            if (Message == null)
                throw new InvalidDataException("Message is a required property for Warning and cannot be null");
            this.Message = Message;
            this.Details = Details;
        }

        /// <summary>
        ///     An warning code that identifies the type of warning that occurred.
        /// </summary>
        /// <value>An warning code that identifies the type of warning that occurred.</value>
        [DataMember(Name = "code", EmitDefaultValue = false)]
        public string Code { get; set; }

        /// <summary>
        ///     A message that describes the warning condition in a human-readable form.
        /// </summary>
        /// <value>A message that describes the warning condition in a human-readable form.</value>
        [DataMember(Name = "message", EmitDefaultValue = false)]
        public string Message { get; set; }

        /// <summary>
        ///     Additional details that can help the caller understand or address the warning.
        /// </summary>
        /// <value>Additional details that can help the caller understand or address the warning.</value>
        [DataMember(Name = "details", EmitDefaultValue = false)]
        public string Details { get; set; }

        /// <summary>
        ///     Returns true if Warning instances are equal
        /// </summary>
        /// <param name="input">Instance of Warning to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Warning input)
        {
            if (input == null)
                return false;

            return
                (
                    Code == input.Code ||
                    (Code != null &&
                     Code.Equals(input.Code))
                ) &&
                (
                    Message == input.Message ||
                    (Message != null &&
                     Message.Equals(input.Message))
                ) &&
                (
                    Details == input.Details ||
                    (Details != null &&
                     Details.Equals(input.Details))
                );
        }

        /// <summary>
        ///     To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }

        /// <summary>
        ///     Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Warning {\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  Details: ").Append(Details).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        ///     Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        ///     Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as Warning);
        }

        /// <summary>
        ///     Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                if (Code != null)
                    hashCode = hashCode * 59 + Code.GetHashCode();
                if (Message != null)
                    hashCode = hashCode * 59 + Message.GetHashCode();
                if (Details != null)
                    hashCode = hashCode * 59 + Details.GetHashCode();
                return hashCode;
            }
        }
    }
}