/*
 * Selling Partner API for Catalog Items
 *
 * The Selling Partner API for Catalog Items helps you programmatically retrieve item details for items in the catalog.
 *
 * OpenAPI spec version: v0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace FikaAmazonAPI.AmazonSpApiSDK.Models.CatalogItems
{
    /// <summary>
    ///     The dimension type attribute of an item.
    /// </summary>
    [DataContract]
    public class DimensionType : IEquatable<DimensionType>, IValidatableObject
    {
        public DimensionType()
        {
        }

        /// <summary>
        ///     Initializes a new instance of the <see cref="DimensionType" /> class.
        /// </summary>
        /// <param name="Height">The height attribute of the dimension..</param>
        /// <param name="Length">The length attribute of the dimension..</param>
        /// <param name="Width">The width attribute of the dimension..</param>
        /// <param name="Weight">The weight attribute of the dimension..</param>
        public DimensionType(DecimalWithUnits Height = default, DecimalWithUnits Length = default,
            DecimalWithUnits Width = default, DecimalWithUnits Weight = default)
        {
            this.Height = Height;
            this.Length = Length;
            this.Width = Width;
            this.Weight = Weight;
        }

        /// <summary>
        ///     The height attribute of the dimension.
        /// </summary>
        /// <value>The height attribute of the dimension.</value>
        [DataMember(Name = "Height", EmitDefaultValue = false)]
        public DecimalWithUnits Height { get; set; }

        /// <summary>
        ///     The length attribute of the dimension.
        /// </summary>
        /// <value>The length attribute of the dimension.</value>
        [DataMember(Name = "Length", EmitDefaultValue = false)]
        public DecimalWithUnits Length { get; set; }

        /// <summary>
        ///     The width attribute of the dimension.
        /// </summary>
        /// <value>The width attribute of the dimension.</value>
        [DataMember(Name = "Width", EmitDefaultValue = false)]
        public DecimalWithUnits Width { get; set; }

        /// <summary>
        ///     The weight attribute of the dimension.
        /// </summary>
        /// <value>The weight attribute of the dimension.</value>
        [DataMember(Name = "Weight", EmitDefaultValue = false)]
        public DecimalWithUnits Weight { get; set; }

        /// <summary>
        ///     Returns true if DimensionType instances are equal
        /// </summary>
        /// <param name="input">Instance of DimensionType to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DimensionType input)
        {
            if (input == null)
                return false;

            return
                (
                    Height == input.Height ||
                    (Height != null &&
                     Height.Equals(input.Height))
                ) &&
                (
                    Length == input.Length ||
                    (Length != null &&
                     Length.Equals(input.Length))
                ) &&
                (
                    Width == input.Width ||
                    (Width != null &&
                     Width.Equals(input.Width))
                ) &&
                (
                    Weight == input.Weight ||
                    (Weight != null &&
                     Weight.Equals(input.Weight))
                );
        }

        /// <summary>
        ///     To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }

        /// <summary>
        ///     Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DimensionType {\n");
            sb.Append("  Height: ").Append(Height).Append("\n");
            sb.Append("  Length: ").Append(Length).Append("\n");
            sb.Append("  Width: ").Append(Width).Append("\n");
            sb.Append("  Weight: ").Append(Weight).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        ///     Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        ///     Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as DimensionType);
        }

        /// <summary>
        ///     Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                if (Height != null)
                    hashCode = hashCode * 59 + Height.GetHashCode();
                if (Length != null)
                    hashCode = hashCode * 59 + Length.GetHashCode();
                if (Width != null)
                    hashCode = hashCode * 59 + Width.GetHashCode();
                if (Weight != null)
                    hashCode = hashCode * 59 + Weight.GetHashCode();
                return hashCode;
            }
        }
    }
}