/*
 * Selling Partner API for Shipping
 *
 * Provides programmatic access to Amazon Shipping APIs.
 *
 * OpenAPI spec version: v1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace FikaAmazonAPI.AmazonSpApiSDK.Models.Shipping
{
    /// <summary>
    ///     The specific rate purchased for the shipment, or null if unpurchased.
    /// </summary>
    [DataContract]
    public class AcceptedRate : IEquatable<AcceptedRate>, IValidatableObject
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="AcceptedRate" /> class.
        /// </summary>
        /// <param name="TotalCharge">The total charge that will be billed for the rate..</param>
        /// <param name="BilledWeight">The weight that was used to calculate the totalCharge..</param>
        /// <param name="ServiceType">ServiceType.</param>
        /// <param name="Promise">Promise.</param>
        public AcceptedRate(Currency TotalCharge = default, Weight BilledWeight = default,
            ServiceType? ServiceType = default, ShippingPromiseSet Promise = default)
        {
            this.TotalCharge = TotalCharge;
            this.BilledWeight = BilledWeight;
            this.ServiceType = ServiceType;
            this.Promise = Promise;
        }

        /// <summary>
        ///     Gets or Sets ServiceType
        /// </summary>
        [DataMember(Name = "serviceType", EmitDefaultValue = false)]
        public ServiceType? ServiceType { get; set; }

        /// <summary>
        ///     The total charge that will be billed for the rate.
        /// </summary>
        /// <value>The total charge that will be billed for the rate.</value>
        [DataMember(Name = "totalCharge", EmitDefaultValue = false)]
        public Currency TotalCharge { get; set; }

        /// <summary>
        ///     The weight that was used to calculate the totalCharge.
        /// </summary>
        /// <value>The weight that was used to calculate the totalCharge.</value>
        [DataMember(Name = "billedWeight", EmitDefaultValue = false)]
        public Weight BilledWeight { get; set; }


        /// <summary>
        ///     Gets or Sets Promise
        /// </summary>
        [DataMember(Name = "promise", EmitDefaultValue = false)]
        public ShippingPromiseSet Promise { get; set; }

        /// <summary>
        ///     Returns true if AcceptedRate instances are equal
        /// </summary>
        /// <param name="input">Instance of AcceptedRate to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AcceptedRate input)
        {
            if (input == null)
                return false;

            return
                (
                    TotalCharge == input.TotalCharge ||
                    (TotalCharge != null &&
                     TotalCharge.Equals(input.TotalCharge))
                ) &&
                (
                    BilledWeight == input.BilledWeight ||
                    (BilledWeight != null &&
                     BilledWeight.Equals(input.BilledWeight))
                ) &&
                (
                    ServiceType == input.ServiceType ||
                    (ServiceType != null &&
                     ServiceType.Equals(input.ServiceType))
                ) &&
                (
                    Promise == input.Promise ||
                    (Promise != null &&
                     Promise.Equals(input.Promise))
                );
        }

        /// <summary>
        ///     To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }

        /// <summary>
        ///     Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AcceptedRate {\n");
            sb.Append("  TotalCharge: ").Append(TotalCharge).Append("\n");
            sb.Append("  BilledWeight: ").Append(BilledWeight).Append("\n");
            sb.Append("  ServiceType: ").Append(ServiceType).Append("\n");
            sb.Append("  Promise: ").Append(Promise).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        ///     Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        ///     Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as AcceptedRate);
        }

        /// <summary>
        ///     Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                if (TotalCharge != null)
                    hashCode = hashCode * 59 + TotalCharge.GetHashCode();
                if (BilledWeight != null)
                    hashCode = hashCode * 59 + BilledWeight.GetHashCode();
                if (ServiceType != null)
                    hashCode = hashCode * 59 + ServiceType.GetHashCode();
                if (Promise != null)
                    hashCode = hashCode * 59 + Promise.GetHashCode();
                return hashCode;
            }
        }
    }
}