/*
 * Selling Partner API for Shipping
 *
 * Provides programmatic access to Amazon Shipping APIs.
 *
 * OpenAPI spec version: v1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace FikaAmazonAPI.AmazonSpApiSDK.Models.Shipping
{
    /// <summary>
    ///     The payload schema for the getRates operation.
    /// </summary>
    [DataContract]
    public class GetRatesResult : IEquatable<GetRatesResult>, IValidatableObject
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="GetRatesResult" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        public GetRatesResult()
        {
        }

        /// <summary>
        ///     Initializes a new instance of the <see cref="GetRatesResult" /> class.
        /// </summary>
        /// <param name="ServiceRates">ServiceRates (required).</param>
        public GetRatesResult(ServiceRateList ServiceRates = default)
        {
            // to ensure "ServiceRates" is required (not null)
            if (ServiceRates == null)
                throw new InvalidDataException(
                    "ServiceRates is a required property for GetRatesResult and cannot be null");
            this.ServiceRates = ServiceRates;
        }

        /// <summary>
        ///     Gets or Sets ServiceRates
        /// </summary>
        [DataMember(Name = "serviceRates", EmitDefaultValue = false)]
        public ServiceRateList ServiceRates { get; set; }

        /// <summary>
        ///     Returns true if GetRatesResult instances are equal
        /// </summary>
        /// <param name="input">Instance of GetRatesResult to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetRatesResult input)
        {
            if (input == null)
                return false;

            return
                ServiceRates == input.ServiceRates ||
                (ServiceRates != null &&
                 ServiceRates.Equals(input.ServiceRates));
        }

        /// <summary>
        ///     To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }

        /// <summary>
        ///     Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GetRatesResult {\n");
            sb.Append("  ServiceRates: ").Append(ServiceRates).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        ///     Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        ///     Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as GetRatesResult);
        }

        /// <summary>
        ///     Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                if (ServiceRates != null)
                    hashCode = hashCode * 59 + ServiceRates.GetHashCode();
                return hashCode;
            }
        }
    }
}