/*
 * Selling Partner API for Shipping
 *
 * Provides programmatic access to Amazon Shipping APIs.
 *
 * OpenAPI spec version: v1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace FikaAmazonAPI.AmazonSpApiSDK.Models.Shipping
{
    /// <summary>
    ///     The shipment related data.
    /// </summary>
    [DataContract]
    public class Shipment : IEquatable<Shipment>, IValidatableObject
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="Shipment" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        public Shipment()
        {
        }

        /// <summary>
        ///     Initializes a new instance of the <see cref="Shipment" /> class.
        /// </summary>
        /// <param name="ShipmentId">ShipmentId (required).</param>
        /// <param name="ClientReferenceId">ClientReferenceId (required).</param>
        /// <param name="ShipFrom">ShipFrom (required).</param>
        /// <param name="ShipTo">ShipTo (required).</param>
        /// <param name="AcceptedRate">AcceptedRate.</param>
        /// <param name="Shipper">Shipper.</param>
        /// <param name="Containers">Containers (required).</param>
        public Shipment(ShipmentId ShipmentId = default, string ClientReferenceId = default, Address ShipFrom = default,
            Address ShipTo = default, AcceptedRate AcceptedRate = default, Party Shipper = default,
            ContainerList Containers = default)
        {
            // to ensure "ShipmentId" is required (not null)
            if (ShipmentId == null)
                throw new InvalidDataException("ShipmentId is a required property for Shipment and cannot be null");
            this.ShipmentId = ShipmentId;
            // to ensure "ClientReferenceId" is required (not null)
            if (ClientReferenceId == null)
                throw new InvalidDataException(
                    "ClientReferenceId is a required property for Shipment and cannot be null");
            this.ClientReferenceId = ClientReferenceId;
            // to ensure "ShipFrom" is required (not null)
            if (ShipFrom == null)
                throw new InvalidDataException("ShipFrom is a required property for Shipment and cannot be null");
            this.ShipFrom = ShipFrom;
            // to ensure "ShipTo" is required (not null)
            if (ShipTo == null)
                throw new InvalidDataException("ShipTo is a required property for Shipment and cannot be null");
            this.ShipTo = ShipTo;
            // to ensure "Containers" is required (not null)
            if (Containers == null)
                throw new InvalidDataException("Containers is a required property for Shipment and cannot be null");
            this.Containers = Containers;
            this.AcceptedRate = AcceptedRate;
            this.Shipper = Shipper;
        }

        /// <summary>
        ///     Gets or Sets ShipmentId
        /// </summary>
        [DataMember(Name = "shipmentId", EmitDefaultValue = false)]
        public ShipmentId ShipmentId { get; set; }

        /// <summary>
        ///     Gets or Sets ClientReferenceId
        /// </summary>
        [DataMember(Name = "clientReferenceId", EmitDefaultValue = false)]
        public string ClientReferenceId { get; set; }

        /// <summary>
        ///     Gets or Sets ShipFrom
        /// </summary>
        [DataMember(Name = "shipFrom", EmitDefaultValue = false)]
        public Address ShipFrom { get; set; }

        /// <summary>
        ///     Gets or Sets ShipTo
        /// </summary>
        [DataMember(Name = "shipTo", EmitDefaultValue = false)]
        public Address ShipTo { get; set; }

        /// <summary>
        ///     Gets or Sets AcceptedRate
        /// </summary>
        [DataMember(Name = "acceptedRate", EmitDefaultValue = false)]
        public AcceptedRate AcceptedRate { get; set; }

        /// <summary>
        ///     Gets or Sets Shipper
        /// </summary>
        [DataMember(Name = "shipper", EmitDefaultValue = false)]
        public Party Shipper { get; set; }

        /// <summary>
        ///     Gets or Sets Containers
        /// </summary>
        [DataMember(Name = "containers", EmitDefaultValue = false)]
        public ContainerList Containers { get; set; }

        /// <summary>
        ///     Returns true if Shipment instances are equal
        /// </summary>
        /// <param name="input">Instance of Shipment to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Shipment input)
        {
            if (input == null)
                return false;

            return
                (
                    ShipmentId == input.ShipmentId ||
                    (ShipmentId != null &&
                     ShipmentId.Equals(input.ShipmentId))
                ) &&
                (
                    ClientReferenceId == input.ClientReferenceId ||
                    (ClientReferenceId != null &&
                     ClientReferenceId.Equals(input.ClientReferenceId))
                ) &&
                (
                    ShipFrom == input.ShipFrom ||
                    (ShipFrom != null &&
                     ShipFrom.Equals(input.ShipFrom))
                ) &&
                (
                    ShipTo == input.ShipTo ||
                    (ShipTo != null &&
                     ShipTo.Equals(input.ShipTo))
                ) &&
                (
                    AcceptedRate == input.AcceptedRate ||
                    (AcceptedRate != null &&
                     AcceptedRate.Equals(input.AcceptedRate))
                ) &&
                (
                    Shipper == input.Shipper ||
                    (Shipper != null &&
                     Shipper.Equals(input.Shipper))
                ) &&
                (
                    Containers == input.Containers ||
                    (Containers != null &&
                     Containers.Equals(input.Containers))
                );
        }

        /// <summary>
        ///     To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }

        /// <summary>
        ///     Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Shipment {\n");
            sb.Append("  ShipmentId: ").Append(ShipmentId).Append("\n");
            sb.Append("  ClientReferenceId: ").Append(ClientReferenceId).Append("\n");
            sb.Append("  ShipFrom: ").Append(ShipFrom).Append("\n");
            sb.Append("  ShipTo: ").Append(ShipTo).Append("\n");
            sb.Append("  AcceptedRate: ").Append(AcceptedRate).Append("\n");
            sb.Append("  Shipper: ").Append(Shipper).Append("\n");
            sb.Append("  Containers: ").Append(Containers).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        ///     Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        ///     Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as Shipment);
        }

        /// <summary>
        ///     Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                if (ShipmentId != null)
                    hashCode = hashCode * 59 + ShipmentId.GetHashCode();
                if (ClientReferenceId != null)
                    hashCode = hashCode * 59 + ClientReferenceId.GetHashCode();
                if (ShipFrom != null)
                    hashCode = hashCode * 59 + ShipFrom.GetHashCode();
                if (ShipTo != null)
                    hashCode = hashCode * 59 + ShipTo.GetHashCode();
                if (AcceptedRate != null)
                    hashCode = hashCode * 59 + AcceptedRate.GetHashCode();
                if (Shipper != null)
                    hashCode = hashCode * 59 + Shipper.GetHashCode();
                if (Containers != null)
                    hashCode = hashCode * 59 + Containers.GetHashCode();
                return hashCode;
            }
        }
    }
}