/*
 * Selling Partner API for FBA Inventory
 *
 * The Selling Partner API for FBA Inventory lets you programmatically retrieve information about inventory in Amazon's fulfillment network.
 *
 * OpenAPI spec version: v1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace FikaAmazonAPI.AmazonSpApiSDK.Models.FbaInventory
{
    /// <summary>
    ///     Inventory summary for a specific item.
    /// </summary>
    [DataContract]
    public class InventorySummary : IEquatable<InventorySummary>, IValidatableObject
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="InventorySummary" /> class.
        /// </summary>
        /// <param name="Asin">The Amazon Standard Identification Number (ASIN) of an item..</param>
        /// <param name="FnSku">Amazon&#39;s fulfillment network SKU identifier..</param>
        /// <param name="SellerSku">The seller SKU of the item..</param>
        /// <param name="Condition">The condition of the item as described by the seller (for example, New Item)..</param>
        /// <param name="InventoryDetails">InventoryDetails.</param>
        /// <param name="LastUpdatedTime">The date and time that any quantity was last updated..</param>
        /// <param name="ProductName">The localized language product title of the item within the specific marketplace..</param>
        /// <param name="TotalQuantity">The total number of units in an inbound shipment or in Amazon fulfillment centers..</param>
        public InventorySummary(string Asin = default, string FnSku = default, string SellerSku = default,
            string Condition = default, InventoryDetails InventoryDetails = default,
            DateTime? LastUpdatedTime = default, string ProductName = default, int? TotalQuantity = default)
        {
            this.Asin = Asin;
            this.FnSku = FnSku;
            this.SellerSku = SellerSku;
            this.Condition = Condition;
            this.InventoryDetails = InventoryDetails;
            this.LastUpdatedTime = LastUpdatedTime;
            this.ProductName = ProductName;
            this.TotalQuantity = TotalQuantity;
        }

        /// <summary>
        ///     The Amazon Standard Identification Number (ASIN) of an item.
        /// </summary>
        /// <value>The Amazon Standard Identification Number (ASIN) of an item.</value>
        [DataMember(Name = "asin", EmitDefaultValue = false)]
        public string Asin { get; set; }

        /// <summary>
        ///     Amazon&#39;s fulfillment network SKU identifier.
        /// </summary>
        /// <value>Amazon&#39;s fulfillment network SKU identifier.</value>
        [DataMember(Name = "fnSku", EmitDefaultValue = false)]
        public string FnSku { get; set; }

        /// <summary>
        ///     The seller SKU of the item.
        /// </summary>
        /// <value>The seller SKU of the item.</value>
        [DataMember(Name = "sellerSku", EmitDefaultValue = false)]
        public string SellerSku { get; set; }

        /// <summary>
        ///     The condition of the item as described by the seller (for example, New Item).
        /// </summary>
        /// <value>The condition of the item as described by the seller (for example, New Item).</value>
        [DataMember(Name = "condition", EmitDefaultValue = false)]
        public string Condition { get; set; }

        /// <summary>
        ///     Gets or Sets InventoryDetails
        /// </summary>
        [DataMember(Name = "inventoryDetails", EmitDefaultValue = false)]
        public InventoryDetails InventoryDetails { get; set; }

        /// <summary>
        ///     The date and time that any quantity was last updated.
        /// </summary>
        /// <value>The date and time that any quantity was last updated.</value>
        [DataMember(Name = "lastUpdatedTime", EmitDefaultValue = false)]
        public DateTime? LastUpdatedTime { get; set; }

        /// <summary>
        ///     The localized language product title of the item within the specific marketplace.
        /// </summary>
        /// <value>The localized language product title of the item within the specific marketplace.</value>
        [DataMember(Name = "productName", EmitDefaultValue = false)]
        public string ProductName { get; set; }

        /// <summary>
        ///     The total number of units in an inbound shipment or in Amazon fulfillment centers.
        /// </summary>
        /// <value>The total number of units in an inbound shipment or in Amazon fulfillment centers.</value>
        [DataMember(Name = "totalQuantity", EmitDefaultValue = false)]
        public int? TotalQuantity { get; set; }

        /// <summary>
        ///     Returns true if InventorySummary instances are equal
        /// </summary>
        /// <param name="input">Instance of InventorySummary to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InventorySummary input)
        {
            if (input == null)
                return false;

            return
                (
                    Asin == input.Asin ||
                    (Asin != null &&
                     Asin.Equals(input.Asin))
                ) &&
                (
                    FnSku == input.FnSku ||
                    (FnSku != null &&
                     FnSku.Equals(input.FnSku))
                ) &&
                (
                    SellerSku == input.SellerSku ||
                    (SellerSku != null &&
                     SellerSku.Equals(input.SellerSku))
                ) &&
                (
                    Condition == input.Condition ||
                    (Condition != null &&
                     Condition.Equals(input.Condition))
                ) &&
                (
                    InventoryDetails == input.InventoryDetails ||
                    (InventoryDetails != null &&
                     InventoryDetails.Equals(input.InventoryDetails))
                ) &&
                (
                    LastUpdatedTime == input.LastUpdatedTime ||
                    (LastUpdatedTime != null &&
                     LastUpdatedTime.Equals(input.LastUpdatedTime))
                ) &&
                (
                    ProductName == input.ProductName ||
                    (ProductName != null &&
                     ProductName.Equals(input.ProductName))
                ) &&
                (
                    TotalQuantity == input.TotalQuantity ||
                    (TotalQuantity != null &&
                     TotalQuantity.Equals(input.TotalQuantity))
                );
        }

        /// <summary>
        ///     To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }

        /// <summary>
        ///     Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InventorySummary {\n");
            sb.Append("  Asin: ").Append(Asin).Append("\n");
            sb.Append("  FnSku: ").Append(FnSku).Append("\n");
            sb.Append("  SellerSku: ").Append(SellerSku).Append("\n");
            sb.Append("  Condition: ").Append(Condition).Append("\n");
            sb.Append("  InventoryDetails: ").Append(InventoryDetails).Append("\n");
            sb.Append("  LastUpdatedTime: ").Append(LastUpdatedTime).Append("\n");
            sb.Append("  ProductName: ").Append(ProductName).Append("\n");
            sb.Append("  TotalQuantity: ").Append(TotalQuantity).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        ///     Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        ///     Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as InventorySummary);
        }

        /// <summary>
        ///     Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                if (Asin != null)
                    hashCode = hashCode * 59 + Asin.GetHashCode();
                if (FnSku != null)
                    hashCode = hashCode * 59 + FnSku.GetHashCode();
                if (SellerSku != null)
                    hashCode = hashCode * 59 + SellerSku.GetHashCode();
                if (Condition != null)
                    hashCode = hashCode * 59 + Condition.GetHashCode();
                if (InventoryDetails != null)
                    hashCode = hashCode * 59 + InventoryDetails.GetHashCode();
                if (LastUpdatedTime != null)
                    hashCode = hashCode * 59 + LastUpdatedTime.GetHashCode();
                if (ProductName != null)
                    hashCode = hashCode * 59 + ProductName.GetHashCode();
                if (TotalQuantity != null)
                    hashCode = hashCode * 59 + TotalQuantity.GetHashCode();
                return hashCode;
            }
        }
    }
}