/*
 * Selling Partner API for Merchant Fulfillment
 *
 * The Selling Partner API for Merchant Fulfillment helps you build applications that let sellers purchase shipping for non-Prime and Prime orders using Amazon’s Buy Shipping Services.
 *
 * OpenAPI spec version: v0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace FikaAmazonAPI.AmazonSpApiSDK.Models.MerchantFulfillment
{
    /// <summary>
    ///     Request schema.
    /// </summary>
    [DataContract]
    public class GetAdditionalSellerInputsRequest : IEquatable<GetAdditionalSellerInputsRequest>, IValidatableObject
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="GetAdditionalSellerInputsRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        public GetAdditionalSellerInputsRequest()
        {
        }

        /// <summary>
        ///     Initializes a new instance of the <see cref="GetAdditionalSellerInputsRequest" /> class.
        /// </summary>
        /// <param name="shippingServiceId">shippingServiceId (required).</param>
        /// <param name="shipFromAddress">The address from which to ship. (required).</param>
        /// <param name="orderId">An Amazon defined order identifier (required).</param>
        public GetAdditionalSellerInputsRequest(string shippingServiceId = default, Address shipFromAddress = default,
            string orderId = default)
        {
            // to ensure "shippingServiceId" is required (not null)
            if (shippingServiceId == null)
                throw new InvalidDataException(
                    "shippingServiceId is a required property for GetAdditionalSellerInputsRequest and cannot be null");
            ShippingServiceId = shippingServiceId;
            // to ensure "shipFromAddress" is required (not null)
            if (shipFromAddress == null)
                throw new InvalidDataException(
                    "shipFromAddress is a required property for GetAdditionalSellerInputsRequest and cannot be null");
            ShipFromAddress = shipFromAddress;
            // to ensure "orderId" is required (not null)
            if (orderId == null)
                throw new InvalidDataException(
                    "orderId is a required property for GetAdditionalSellerInputsRequest and cannot be null");
            OrderId = orderId;
        }

        /// <summary>
        ///     Gets or Sets ShippingServiceId
        /// </summary>
        [DataMember(Name = "ShippingServiceId", EmitDefaultValue = false)]
        public string ShippingServiceId { get; set; }

        /// <summary>
        ///     The address from which to ship.
        /// </summary>
        /// <value>The address from which to ship.</value>
        [DataMember(Name = "ShipFromAddress", EmitDefaultValue = false)]
        public Address ShipFromAddress { get; set; }

        /// <summary>
        ///     An Amazon defined order identifier
        /// </summary>
        /// <value>An Amazon defined order identifier</value>
        [DataMember(Name = "OrderId", EmitDefaultValue = false)]
        public string OrderId { get; set; }

        /// <summary>
        ///     Returns true if GetAdditionalSellerInputsRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of GetAdditionalSellerInputsRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetAdditionalSellerInputsRequest input)
        {
            if (input == null)
                return false;

            return
                (
                    ShippingServiceId == input.ShippingServiceId ||
                    (ShippingServiceId != null &&
                     ShippingServiceId.Equals(input.ShippingServiceId))
                ) &&
                (
                    ShipFromAddress == input.ShipFromAddress ||
                    (ShipFromAddress != null &&
                     ShipFromAddress.Equals(input.ShipFromAddress))
                ) &&
                (
                    OrderId == input.OrderId ||
                    (OrderId != null &&
                     OrderId.Equals(input.OrderId))
                );
        }

        /// <summary>
        ///     To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }

        /// <summary>
        ///     Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GetAdditionalSellerInputsRequest {\n");
            sb.Append("  ShippingServiceId: ").Append(ShippingServiceId).Append("\n");
            sb.Append("  ShipFromAddress: ").Append(ShipFromAddress).Append("\n");
            sb.Append("  OrderId: ").Append(OrderId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        ///     Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        ///     Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as GetAdditionalSellerInputsRequest);
        }

        /// <summary>
        ///     Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                if (ShippingServiceId != null)
                    hashCode = hashCode * 59 + ShippingServiceId.GetHashCode();
                if (ShipFromAddress != null)
                    hashCode = hashCode * 59 + ShipFromAddress.GetHashCode();
                if (OrderId != null)
                    hashCode = hashCode * 59 + OrderId.GetHashCode();
                return hashCode;
            }
        }
    }
}