/*
 * Selling Partner API for Fulfillment Inbound
 *
 * The Selling Partner API for Fulfillment Inbound lets you create applications that create and update inbound shipments of inventory to Amazon's fulfillment network.
 *
 * OpenAPI spec version: v0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace FikaAmazonAPI.AmazonSpApiSDK.Models.FulfillmentInbound
{
    /// <summary>
    ///     CreateInboundShipmentPlanResult
    /// </summary>
    [DataContract]
    public class CreateInboundShipmentPlanResult : IEquatable<CreateInboundShipmentPlanResult>, IValidatableObject
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="CreateInboundShipmentPlanResult" /> class.
        /// </summary>
        /// <param name="inboundShipmentPlans">inboundShipmentPlans.</param>
        public CreateInboundShipmentPlanResult(InboundShipmentPlanList inboundShipmentPlans = default)
        {
            InboundShipmentPlans = inboundShipmentPlans;
        }

        /// <summary>
        ///     Gets or Sets InboundShipmentPlans
        /// </summary>
        [DataMember(Name = "InboundShipmentPlans", EmitDefaultValue = false)]
        public InboundShipmentPlanList InboundShipmentPlans { get; set; }

        /// <summary>
        ///     Returns true if CreateInboundShipmentPlanResult instances are equal
        /// </summary>
        /// <param name="input">Instance of CreateInboundShipmentPlanResult to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateInboundShipmentPlanResult input)
        {
            if (input == null)
                return false;

            return
                InboundShipmentPlans == input.InboundShipmentPlans ||
                (InboundShipmentPlans != null &&
                 InboundShipmentPlans.Equals(input.InboundShipmentPlans));
        }

        /// <summary>
        ///     To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }

        /// <summary>
        ///     Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CreateInboundShipmentPlanResult {\n");
            sb.Append("  InboundShipmentPlans: ").Append(InboundShipmentPlans).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        ///     Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        ///     Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as CreateInboundShipmentPlanResult);
        }

        /// <summary>
        ///     Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                if (InboundShipmentPlans != null)
                    hashCode = hashCode * 59 + InboundShipmentPlans.GetHashCode();
                return hashCode;
            }
        }
    }
}