/*
 * Selling Partner API for Fulfillment Inbound
 *
 * The Selling Partner API for Fulfillment Inbound lets you create applications that create and update inbound shipments of inventory to Amazon's fulfillment network.
 *
 * OpenAPI spec version: v0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace FikaAmazonAPI.AmazonSpApiSDK.Models.FulfillmentInbound
{
    /// <summary>
    ///     Dimension and weight information for the package.
    /// </summary>
    [DataContract]
    public class PartneredSmallParcelPackageInput : IEquatable<PartneredSmallParcelPackageInput>, IValidatableObject
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="PartneredSmallParcelPackageInput" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        public PartneredSmallParcelPackageInput()
        {
        }

        /// <summary>
        ///     Initializes a new instance of the <see cref="PartneredSmallParcelPackageInput" /> class.
        /// </summary>
        /// <param name="dimensions">dimensions (required).</param>
        /// <param name="weight">weight (required).</param>
        public PartneredSmallParcelPackageInput(Dimensions dimensions = default, Weight weight = default)
        {
            // to ensure "dimensions" is required (not null)
            if (dimensions == null)
                throw new InvalidDataException(
                    "dimensions is a required property for PartneredSmallParcelPackageInput and cannot be null");
            Dimensions = dimensions;
            // to ensure "weight" is required (not null)
            if (weight == null)
                throw new InvalidDataException(
                    "weight is a required property for PartneredSmallParcelPackageInput and cannot be null");
            Weight = weight;
        }

        /// <summary>
        ///     Gets or Sets Dimensions
        /// </summary>
        [DataMember(Name = "Dimensions", EmitDefaultValue = false)]
        public Dimensions Dimensions { get; set; }

        /// <summary>
        ///     Gets or Sets Weight
        /// </summary>
        [DataMember(Name = "Weight", EmitDefaultValue = false)]
        public Weight Weight { get; set; }

        /// <summary>
        ///     Returns true if PartneredSmallParcelPackageInput instances are equal
        /// </summary>
        /// <param name="input">Instance of PartneredSmallParcelPackageInput to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PartneredSmallParcelPackageInput input)
        {
            if (input == null)
                return false;

            return
                (
                    Dimensions == input.Dimensions ||
                    (Dimensions != null &&
                     Dimensions.Equals(input.Dimensions))
                ) &&
                (
                    Weight == input.Weight ||
                    (Weight != null &&
                     Weight.Equals(input.Weight))
                );
        }

        /// <summary>
        ///     To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }

        /// <summary>
        ///     Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PartneredSmallParcelPackageInput {\n");
            sb.Append("  Dimensions: ").Append(Dimensions).Append("\n");
            sb.Append("  Weight: ").Append(Weight).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        ///     Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        ///     Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as PartneredSmallParcelPackageInput);
        }

        /// <summary>
        ///     Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                if (Dimensions != null)
                    hashCode = hashCode * 59 + Dimensions.GetHashCode();
                if (Weight != null)
                    hashCode = hashCode * 59 + Weight.GetHashCode();
                return hashCode;
            }
        }
    }
}