/*
 * Selling Partner API for Pricing
 *
 * The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer information for Amazon Marketplace products.
 *
 * OpenAPI spec version: v0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace FikaAmazonAPI.AmazonSpApiSDK.Models.ProductPricing
{
    /// <summary>
    ///     Points
    /// </summary>
    [DataContract]
    public class Points : IEquatable<Points>, IValidatableObject
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="Points" /> class.
        /// </summary>
        /// <param name="PointsNumber">The number of points..</param>
        /// <param name="PointsMonetaryValue">The monetary value of the points..</param>
        public Points(int? PointsNumber = default, MoneyType PointsMonetaryValue = default)
        {
            this.PointsNumber = PointsNumber;
            this.PointsMonetaryValue = PointsMonetaryValue;
        }

        /// <summary>
        ///     The number of points.
        /// </summary>
        /// <value>The number of points.</value>
        [DataMember(Name = "PointsNumber", EmitDefaultValue = false)]
        public int? PointsNumber { get; set; }

        /// <summary>
        ///     The monetary value of the points.
        /// </summary>
        /// <value>The monetary value of the points.</value>
        [DataMember(Name = "PointsMonetaryValue", EmitDefaultValue = false)]
        public MoneyType PointsMonetaryValue { get; set; }

        /// <summary>
        ///     Returns true if Points instances are equal
        /// </summary>
        /// <param name="input">Instance of Points to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Points input)
        {
            if (input == null)
                return false;

            return
                (
                    PointsNumber == input.PointsNumber ||
                    (PointsNumber != null &&
                     PointsNumber.Equals(input.PointsNumber))
                ) &&
                (
                    PointsMonetaryValue == input.PointsMonetaryValue ||
                    (PointsMonetaryValue != null &&
                     PointsMonetaryValue.Equals(input.PointsMonetaryValue))
                );
        }

        /// <summary>
        ///     To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }

        /// <summary>
        ///     Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Points {\n");
            sb.Append("  PointsNumber: ").Append(PointsNumber).Append("\n");
            sb.Append("  PointsMonetaryValue: ").Append(PointsMonetaryValue).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        ///     Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        ///     Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as Points);
        }

        /// <summary>
        ///     Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                if (PointsNumber != null)
                    hashCode = hashCode * 59 + PointsNumber.GetHashCode();
                if (PointsMonetaryValue != null)
                    hashCode = hashCode * 59 + PointsMonetaryValue.GetHashCode();
                return hashCode;
            }
        }
    }
}